language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t cpaun/docker-react -f Dockerfile.dev .

script:
  - docker run cpaun/docker-react npm run test -- --coverage